(function () {
    var params = {
        rssmikle_url: "https://www.guildwars2.com/en/feed/?__utma=25938722.888116290.1431679595.1431679595.1431679595.1&__utmb=25938722.4.9.1431679611703&__utmc=25938722&__utmx=-&__utmz=25938722.1431679595.1.1.utmcsr=google%7Cutmccn=(organic)%7Cutmcmd=organic%7Cutmctr=(not%20provided)&__utmv=-&__utmk=198832364/",
        rssmikle_frame_width: "100%",
        rssmikle_frame_height: "400",
        frame_height_by_article: "3",
        rssmikle_target: "_blank",
        rssmikle_font: "Arial, Helvetica, sans-serif",
        rssmikle_font_size: "12",
        rssmikle_border: "off",
        responsive: "on",
        rssmikle_css_url: "",
        text_align: "left",
        text_align2: "left",
        corner: "on",
        scrollbar: "on",
        autoscroll: "off",
        scrolldirection: "up",
        scrollstep: "3",
        mcspeed: "20",
        sort: "New",
        rssmikle_title: "on",
        rssmikle_title_sentence: "Guild Wars 2 News!",
        rssmikle_title_link: "",
        rssmikle_title_bgcolor: "#5CB85C",
        rssmikle_title_color: "#FFFFFF",
        rssmikle_title_bgimage: "",
        rssmikle_item_bgcolor: "transparent",
        rssmikle_item_bgimage: "",
        rssmikle_item_title_length: "55",
        rssmikle_item_title_color: "#FFFFFF",
        rssmikle_item_border_bottom: "on",
        rssmikle_item_description: "on",
        item_link: "off",
        rssmikle_item_description_length: "150",
        rssmikle_item_description_color: "#FFFFFF",
        rssmikle_item_date: "gl1",
        rssmikle_timezone: "Etc/GMT",
        datetime_format: "%b %e, %Y %l:%M:%S %p",
        item_description_style: "text", item_thumbnail: "full",
        item_thumbnail_selection: "auto", article_num: "15",
        rssmikle_item_podcast: "off",
        keyword_inc: "",
        keyword_exc: ""
    };
    feedwind_show_widget_iframe(params);
})();